MiniMoodle/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from django.views.generic import RedirectView


urlpatterns = [
	path('', RedirectView.as_view(url='/moodle/')),
	path('moodle/', include('moodle.urls')),
	path('login/', auth_views.login,name='login'),
	path('logout/',auth_views.logout,{'next_page':'login'},name='logout'),
    path('admin/', admin.site.urls),
]

moodle/urls.py
from django.urls import path
from django.conf.urls import url
from . import views

urlpatterns = [
	path('',views.home,name='home'),
	path('courses/',views.courses,name='courses'),
	url(r'^courses/(?P<pk>\w+)/$',views.courseDetail,name='course-detail'),
	url(r'^courses/(?P<pk>\w+)/enroll/$',views.courseEnroll,name='enroll'),
	url(r'^courses/(?P<pk>\w+)/drop/$',views.courseDrop,name='drop'),
	url(r'^courses/(?P<pk>\w+)/delete/$',views.courseDelete,name='delete'),
	path('newcourse/',views.newCourse,name='new-course'),
	url(r'^message/(?P<pk>[-\w]+)/delete/$',views.msgDelete,name='msg-delete'),
	path('newuser/',views.newUser,name='new-user'),
	path('allcourses/',views.allcourses,name='allcourses'),
]

moodle/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
import uuid

# Create your models here.

class Course(models.Model):
	"""Model representing a course"""
	name = models.CharField(max_length=6,primary_key=True)
	professor = models.OneToOneField(User,blank=False,null=False,on_delete=models.CASCADE,related_name="courses")
	student =models.ManyToManyField(User,blank=True)
	limit = models.PositiveIntegerField(blank=False)

	def __str__(self):
		return self.name
	
	def get_absolute_url(self):
		return reverse('course-detail',args=[str(self.name)])

class Message(models.Model):
	id = models.UUIDField(primary_key=True, default=uuid.uuid4,)
	title=models.CharField(max_length=100,blank=False)
	content=models.CharField(max_length=500,blank=False)
	course=models.ForeignKey(Course,blank=False,null=False,on_delete=models.CASCADE)
	timestamp=models.DateTimeField(auto_now=True)

	def __str__(self):
		return self.title
		
		
class EnrollTime(models.Model):
	id = models.UUIDField(primary_key=True, default=uuid.uuid4)
	enrolltime=models.DateTimeField(auto_now=True)
	stud= models.ForeignKey(User,on_delete=models.CASCADE,blank=False,null =False)
	relcourse=models.ForeignKey(Course,on_delete=models.CASCADE,blank=False, null = False)

moodle/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class NewCourse(forms.Form):
	name=forms.CharField(required=True,label='Course Name',widget=forms.TextInput(attrs={'maxlength':'6','class':'form-control'}))
	limit = forms.IntegerField(required=True,label='Maximum Strength',widget=forms.NumberInput(attrs={'min':'1','class':'form-control'}))


class NewPost(forms.Form):
	title=forms.CharField(max_length=100,required=True,label='',widget=forms.TextInput(attrs={ 'placeholder':'Title','style':'width:100%','class':'form-control'}))
	content=forms.CharField(max_length =500, required =True,label='' ,widget=forms.Textarea(attrs={ 'placeholder':'Post', 'style':'resize:none;height:150px','class':'form-control'}))


GROUP_CHOICES=[
	('Professor','Professor'),
	('Student','Student'),
]


class NewUser(UserCreationForm):
	group=forms.CharField(required=True,widget=forms.Select(choices=GROUP_CHOICES,attrs={'default':None,'class':'form-control'}))
	lname=forms.CharField(required=True)
	fname=forms.CharField(required=True)
	class Meta:
		model = User
		fields = ('username','fname','lname','password1','password2','group')

moodle/views.py
from django.shortcuts import render, redirect,reverse, get_object_or_404
from .models import Course,Message,EnrollTime
from .forms import NewCourse, NewPost, NewUser
from django.contrib.auth.decorators import login_required, user_passes_test
from django.contrib.auth.models import User,Group
from datetime import datetime,timedelta
from django.contrib import messages
# Create your views here.


'''Not views, just helper functions'''
def group(name,request):
	return request.user.groups.filter(name=name).exists()
	

def is_professor(user):
	return 'Professor' == user.groups.all()[0].name

def is_student(user):
	return 'Student' == user.groups.all()[0].name
	
def is_admin(user):
	return 'admin'== user.username
	
	
	
'''Views'''

	
@login_required
def home(request):
	'''Home page'''

	posts= Message.objects.exclude(timestamp__lt=(datetime.now()-timedelta(days=1)))
	return render( 
		request, 'home.html' , 
		context = { 'courses':courses , 
		'student':group('Student',request),'professor':group('Professor',request),'posts':posts}
	)


@login_required
@user_passes_test(is_student,'home','')
def courses(request):
	'''Page with all the courses in which student has enrolled'''
	
	courses= Course.objects.filter(student__username=request.user.username)
	return render( 
		request, 
		'courses.html' , 
		context = {'courses':courses,'student':group('Student',request)} 
	)
	

@login_required	
def allcourses(request):
	courses=Course.objects.all()
	return render(
		request, 
		'allcourses.html',
		context = {'courses':courses,'student':group('Student',request),'professor':group('Professor',request)}
	)
	

@login_required	
def courseDetail(request,pk):
	course = get_object_or_404(Course,pk=pk)
	posts= Message.objects.filter(course=course)
	
	full =(course.student.all().count()==course.limit)
	#If the user is a student
	if request.user.groups.all()  and 'Student' == request.user.groups.all()[0].name:
	
		enrolled=request.user in course.student.all()
		#getting enroll time for the student if he is enrolled in the course
		if enrolled:
			enrollt=EnrollTime.objects.filter(relcourse=course).filter(stud=request.user)[0].enrolltime
		else:
			enrollt=datetime.now()
			
		#This queryset contains messages only after the enrollement time
		msg_stud=Message.objects.filter(course=course).filter(timestamp__gt=enrollt)
		
		return render(
			request, 
			'course_student.html',
			context = {'course':course,'enrolled':enrolled,'posts':msg_stud,'student':group('Student',request),'full':full}
		)
	
	#If the user is professor
	else:
	
		#If he is the course professor
		if request.user == course.professor:
		
			if request.method=="POST":
				form=NewPost(request.POST)
		
				if form.is_valid():
					title=form.cleaned_data['title']
					content=form.cleaned_data['content']
					
					message=Message(title=title,content=content,course=request.user.courses)
					message.save()
					
					form=NewPost()
					
					return redirect('course-detail',course.name)
					
			else:
				form = NewPost()

			return render(
				request,
				'course_professor.html',
				 context={'form':form,'posts':posts,'course':course,'check':request.user == course.professor,'professor':True}
			)
			
		# If he is not the course professor
		else:
			return render(
				request , 
				'course_professor.html',				
				context={'course':course,'professor':True,}
			)
		
				
#proxy view for enrolling into a course
@login_required
@user_passes_test(is_student,'home','')
def courseEnroll(request,pk):
	course = get_object_or_404(Course,pk=pk)
	
	course.student.add(request.user)
	course.save()
	
	time=EnrollTime(stud=request.user,relcourse=course)
	time.save()
	return redirect( 'course-detail', course.name)
	

#proxy view for dropping out of a courses
@login_required	
@user_passes_test(is_student,'home','')
def courseDrop(request,pk):
	course = get_object_or_404(Course,pk=pk)
	
	course.student.remove(request.user)
	course.save()
	
	time=EnrollTime.objects.filter(relcourse=course).filter(stud=request.user)[0]
	time.delete()
	
	return redirect( 'course-detail', course.name)


#proxy view for deleting a course
@login_required	
@user_passes_test(is_professor,'home','')
def courseDelete(request,pk):
	course=get_object_or_404(Course,pk=pk)
	if course.professor==request.user:
		course.delete()
		return redirect('new-course')
	else:
		return redirect('home')


@login_required
@user_passes_test(is_professor,'home','')
def newCourse(request):

	if request.method=='POST':
		form=NewCourse(request.POST)
	
		if form.is_valid():
			name=request.POST.get('name')
			limit=request.POST.get('limit')
			
			if Course.objects.filter(name=name).exists():
				form=NewCourse()
				course=Course.objects.filter(name=name)
				messages.add_message(request,messages.ERROR, 'Course with this name has already been offered by'+course.professor.first_name+course.professor.last_name)
				return redirect('new-course')
			else:
				course=Course(name=name,professor=request.user,limit=limit)
				course.save()
				messages.add_message(request,messages.INFO, 'Created a new course')

				return redirect(
					'course-detail',
					course.name
				)
	else:
		form=NewCourse()	
	
	return render( 
		request, 
		'new_course.html',
		context = {'form':form,'professor':True}
	)
	

#proxy view for deleting a message
@user_passes_test(is_professor,'home','')
def msgDelete(request,pk):
	message=get_object_or_404(Message,pk=pk)
	message.delete()
	
	return redirect(
		'course-detail',
		request.user.courses
	)
	
	
	
#view for admin to create new user
@user_passes_test(is_admin,'home','')
def newUser(request):
	if request.method=="POST":
		form=NewUser(request.POST)
		if form.is_valid():
			if not User.objects.filter(username=form.cleaned_data.get('username')).exists():
				user=form.save()
				user.refresh_from_db()
				group=Group.objects.get(name=form.cleaned_data.get('group'))
				fname=form.cleaned_data.get('fname')
				lname=form.cleaned_data.get('lname')
				user.first_name=fname
				user.last_name=lname
				group.user_set.add(user)
				user.save()
				messages.add_message(request,messages.INFO,'New User added')
				return redirect(
					'home'
					)
			
			else:
				return redirect('new-user')
		else:
			return render(request,
				'new_user.html',
				context={'form':form}
				)
	else:
		form=NewUser()
		return render( 
			request,
			'new_user.html',
			context={'form':form}
			)

moodle/templates/allcourses.html
{% extends 'base.html' %}
{% block content %}
<h4>All Courses</h4>
<ul>
{% for course in courses %}
<li style="display:block"><p><span class="glyphicon glyphicon-chevron-right"></span>
<a href="{{ course.get_absolute_url }}" {% ifequal user.courses.name course.name %} style="color:orange"{% endifequal %}>{{course.name}}</a></p></li>
{% endfor %}
{% endblock %}

moodle/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <title>MiniMoodle</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  <style>
    /* Remove the navbar's default margin-bottom and rounded borders */ 
    .navbar {
      margin-bottom: 0;
      border-radius: 0;
    }
    
    /* Set height of the grid so .sidenav can be 100% (adjust as needed) */
    .row.content {height: 450px}
    
    /* Set gray background color and 100% height */
    .sidenav {
      padding-top: 20px;
      background-color: #f1f1f1;
      height: 100%;
      overflow:scroll;
    }
    .form-control{
    width:70%;
    }
    /* Set black background color, white text and some padding */
    footer {
      background-color: #555;
      color: white;
      padding: 1px;
      position:fixed;
      bottom:0;
      width:100%;
    }
    
    .btn-success{
    padding-top:4px;
    height:30px;
    padding-right:50px;
    padding-left:50px;
    }
    
    /* On small screens, set height to 'auto' for sidenav and grid */
    @media screen and (max-width: 767px) {
      .sidenav {
        height: auto;
        padding: 15px;
      }
      .row.content {height:auto;} 
    }
  </style>
</head>
<body>

<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>                        
      </button>
      <a class="navbar-brand" href="{% url 'home' %}">Moodle</a>
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav navbar-right">
				{% if user.is_authenticated %}
				<li><a href="{% url 'logout' %}"><span class="glyphicon glyphicon-log-out"></span>Logout</a></li>
        {% endif %}
      </ul>
    </div>
  </div>
</nav>
  
<div class="container-fluid text-center">    
  <div class="row content">
    <div class="col-sm-2 sidenav">
    {% if user.is_authenticated %}
    <h4>Navigation</h4>
      {% if student %}
				<p><a href="{% url 'courses' %}">My Courses</a>
			{% elif professor %}
				<p><a href="{% url 'new-course' %}">Float a New Course</a>
			{% else %}
				<p><a href ="{% url 'new-user' %}">Create New User</a>
			{% endif %}
				<p><a href="{% url 'allcourses' %}">All Courses</a>
   	{%else%}
   	{% endif%}
    </div>
    <div class="col-sm-8 text-left">
    	{% if messages%}
    	{% for message in messages%}
    	<div class="well">
    	{{message}}
    	</div>
    	{% endfor %}
    	{%endif%}
    	<p> 
      {% block content %}
      {% endblock %}
     	</p>
      <hr>
    </div>
    <div class="col-sm-2 sidenav">
{% block sidefeed %}
{% endblock %}
    </div>
  </div>
</div>

<footer class="container-fluid text-center fixed-bottom">
  <p>Created By Divyansh Verma</p>
</footer>

</body>
</html>

moodle/templates/course_enrolled.html
{% extends 'base.html' %}
	{% block content %}
	<h3>{{course.name}}</h3>
	Course offered by Professor <span style="color:orange">{{course.professor.first_name}}&nbsp{{course.professor.last_name}}</span><br>
	{% if student %}
		<a href="{% url 'drop' pk=course.name %}"><button>Drop</button></a><br><br>
	{% endif %}
	{% if messages %}
	<div class= "container-fluid" >
		{% for message in messages %}
		<div class="row">
			<div class="col-sm-5">
			<h5>{{message.title}}</h5>
			</div>
			<div class ="row-sm-7">
			{{message.timestamp}}
			</div>
		</div>
		<div class="row">
			<div class="col-sm-7" >{{message.content}}
			<hr style="display:block"></hr>
			</div>
		</div>
		
		{% endfor %}
	</div>
	{% endif %}
{% endblock %}

moodle/templates/course_professor.html
{% extends 'base.html' %}
	{% block content %}
	<h3>{{course.name}}</h3>
	Course offered by Professor <span style="color:orange">{{course.professor.first_name}}&nbsp{{course.professor.last_name}}</span><br>
Students enrolled: {{course.student.all.count}}<br>
Maximum Strength: {{ course.limit }}<br>
<hr>

{% if check %}
	<h4>Post a message</h4><br>
	<div class="text-center">
		<form method="Post">
		{% csrf_token %}
			<div class="form-group">
				{{form.title.label}}
				{{ form.title }}
			</div>
			<div class="form-group">
				{{ form.content}}
			</div>
			<input type="submit" value="POST" class="btn btn-info btn-sm" >
		</form><br>
	</div>
	<h4><strong>Earlier Posts</strong></h4>
	<hr>
	{% if posts %}
	<div class= "container-fluid" >
		{% for post in posts %}
			<div class="row">
				<div class="col-sm-12">
					<h4>{{post.title}}</h4>
				</div>
			</div>
			<div class="row">
				<div class="col-sm-8" >{{post.content}}<br>
				</div>
			</div>
			<div class="row">
				<div class="col-sm-8" >{{post.timestamp}}<br>
				</div>
				<div class="col-sm-1">
					<a href="{% url 'msg-delete' post.id %}"><button class="btn btn-danger">Remove</button></a>
				</div>
			</div>
			<hr>
		{% endfor %}
	</div>
	{% else %}
		<p> There are no posts to show</p> 	
	{% endif %}

{% endif %}
{% endblock %}

moodle/templates/course_student.html
{% extends 'base.html' %}
{% block content %}
	<h2>{{course.name}}</h2>
	Course Coordinator: Professor <span style="color:orange">{{course.professor.first_name}}&nbsp{{course.professor.last_name}}</span><br>
	Students enrolled: {{course.student.all.count}}<br>
	Maximum Strength: {{ course.limit}}<br>
	{% if enrolled %}
		<a href="{% url 'drop' pk=course.name %}"><button class="btn btn-info">Drop</button></a><br><br>
		<h4><strong>Posts from professor</strong></h4>	
		{% if posts %}
			
			<div class= "container-fluid" >
				{% for post in posts %}
					<div class="row">
						<div class="col-sm-5">
							<h5>{{post.title}}</h5>
						</div>
						<div class ="row-sm-7">
							{{post.timestamp}}
						</div>
					</div>
					<div class="row">
						<div class="col-sm-7" >{{post.content}}
							<hr style="display:block"></hr>
						</div>
					</div>
				{% endfor %}
			</div>
		{% else %}
			There are no posts from the professor
		{% endif %}
	{% elif full %}
		<i><strong> All seats are full. You can not enroll in this course right now</i></strong>
	{% else %}
		<a href="{% url 'enroll' pk=course.name %}"><button class="btn btn-info">Enroll</button></a><br><br>
	{% endif %}
{% endblock %}
{% block sidefeed %}
{% endblock %}

moodle/templates/courses.html
{% extends 'base.html' %}
{% block content %}
{% if student %}
{% if courses %}
<h4>My Courses</h4>
<ul>
{% for course in courses %}
<li style="display:block"><span class="glyphicon glyphicon-chevron-right"><a href="{{ course.get_absolute_url }}">{{course.name}}</a></span></li>
{% endfor %}
</ul>
{% else %}
<span>You have not enrolled in any courses</span>
{% endif %}
{% else %}
You are not authorised to view this page. Please <a href="{% url 'logout' %}">login</a> from an account which is.
{% endif %}
{% endblock %}

moodle/templates/home.html
{% extends "base.html" %}
{% block content %}
<h3>Welcome {{user.first_name}} {{user.last_name}}</h3>
<p>
{% if user.courses %} Your course: <a href="{% url 'course-detail' user.courses %}" style="color:orange">{{user.courses}}</a>{% endif %}
</p>

{% endblock %}

{% block sidefeed %}
	{% if student %}
		<strong>Recent posts</strong><br>
		{% for post in posts%}
			{%if post.course in user.course_set.all%}
				<div class="well">
					<p><a href="{%url 'course-detail' message.course %}">{{message.course}}</a></p>
					<strong>{{post.title}}</strong>
					{% if post.content|make_list|length > 20 %}
					{{post.content|make_list|slice:':18'|join:''}}...
					{%else%}{{post.content}}
					{%endif%}<br>
					{{post.timestamp}}
				</div>
			{% endif%}
		{% endfor %}
	{%endif%}
{%endblock%}

moodle/templates/new_course.html
{% extends 'base.html' %}
{% block content %}
	{%if student %}
		You are not authorised to see this.
	{% else %}
	{% if user.courses %}
		<p>
			You have already floated course <a href="{% url 'course-detail' user.courses %}" style="color:orange">{{user.courses}}</a>.
		</p>
		<p>
			If you want to float another course you have to <a href="{% url 'delete' user.courses%}"><span style="color:red"> delete</span></a> the existing course.
		</p> 
	{% else %}
		<h4> Float a New Course</h4><br>
		<form method='Post'>		
			{% csrf_token %}
			<div class="form-group">
			{{form.name.label}}: {{form.name}}
			</div>
			<div class="form-group">
			{{form.limit.label}}: {{form.limit}}
			</div>
			<div class="text-center"><input type="submit" value="Float" class="btn btn-info"></div>
		</form>
	{% endif %}
{% endif %}
{% endblock %} 

moodle/templates/new_user.html
{% extends 'base.html' %}
{% block content %}
{{form.non_field_errors}}
<div class = "container-fluid">
	<form method="Post">
	{{form.non_field_errors}}
	{% csrf_token %}
	<div class="form-group">
		{{ form.username.label}} <span style="color:red">{{form.username.errors.as_text}}</span><input type="text" name="username" class="form-control" placeholder="Enter a username" >
		</div>
		<div class="form-group">
		Firstname <span style="color:red">{{form.fname.errors.as_text}}</span><input type="text" name="fname" class="form-control"  placeholder="Enter your first name" >
		</div><div class="form-group">
		Lastname <span style="color:red">{{form.lname.errors.as_text}}</span><input type="text" name="lname" class="form-control"  placeholder="Enter your last name" >
		</div>
		<div class="form-group">
		Password <span style="color:red">{{form.password1.errors.as_text}}</span><br><input type="password" name="password1" class="form-control"  placeholder="Enter a secureassword" >
		</div><div class="form-group">
		Confirm password <span style="color:red">{{form.password2.errors.as_text}}</span><br><input type="password" name="password2" class="form-control" placeholder="Confirm password" >
		</div>
		<div class="form-group">
		{{ form.group.label}} <span style="color:red">{{form.group.errors.as_text}}</span>{{ form.group}}
		</div>
	<input type="submit" value="Create" class="btn btn-info">
</form>
</div>
{% endblock %}